### ISSUE TITLE
Get Trip Planner page working with selecting a Trip and having the selection persist with each POST

### ISSUE THREAD

**Issue by mingusmingusmingusmingusmingus** [jessa9000/fieldtrip-planner#10]
Rendering the initial page load in other pages have relied on pulling known data from a table so those were pretty straightforward. Trip Planner is different in that before any tables can load, a user has to input a Trip to match a tripID. Submitting info in the forms re-render the page and I haven't figured out how to order things so that the selected Trip/tripID persists and loads correctly.

The easiest option that I can think of is to just make a dedicated page where a user selects a Trip, which will redirect to another page where all INSERTS and UPDATES are relevant to the selected Trip. If another Trip needs editing, users can go back to that initial page.

**Comment by jessa9000** [comment]
Last night I read this and thought redirecting was a good solution. But it just occurred to me that if we do that, then I don't think the Trip Planner page will satisfy the filter requirement in the CS340 Project Guide. 

Maybe rather than handle the Trip with a form and a POST route, maybe we could do the whole thing client side. I haven't thought this all the way out but here's a relevant [discussion](https://stackoverflow.com/questions/8368002/search-filter-should-i-do-it-client-side-or-server-side).

**Comment by mingusmingusmingusmingusmingus** [comment]
Good point about the filter requirement. I've seen another group handle it by initially rendering the entire table as they did on other pages, then having the filter be its own thing where you select what you want and the page reloads to show just the filtered row. I don't think we need to condition the initial page load on a filter since the INSERT and UPDATE forms don't rely on it.

**Comment by jessa9000** [comment]
Out of scope
